apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transmission
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 5703cadf-6efb-41cb-bbce-b2ee0006cf1b
        property: password
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 5703cadf-6efb-41cb-bbce-b2ee0006cf1b
        property: username