apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: shared-nfs-pv
  storageClassName: nfs-client
