apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizarr-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/service.scheme: http
spec:
  tls:
    - hosts:
        - wizarr.tanksrop.xyz
      secretName: tanksrop.xyz
  rules:
  - host: wizarr.tanksrop.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wizarr
            port:
              number: 80