apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: shared-nfs-pv
  storageClassName: nfs-client
