authentik:
  secret_key: "env://AUTHENTIK_SECRET_KEY"
  error_reporting:
    enabled: false
  postgresql:
    password: "env://AUTHENTIK_POSTGRESQL__PASSWORD"

server:
  ingress:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: "authentik"
    database: "authentik"
    existingSecret: "authentik-credentials"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "postgres-password"

global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-credentials
          key: authentik-key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-credentials
          key: postgres-password
