authentik:
  secret_key: ""
  error_reporting:
    enabled: false
server:
  ingress:
    enabled: false
postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-secrets
    secretKeys:
      adminPasswordKey: postgresql-password
      userPasswordKey: postgresql-password
redis:
  enabled: false
