apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: media
  name: tanksrop.xyz
spec:
  secretName: tanksrop.xyz
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.tanksrop.xyz'
  dnsNames:
  - '*.tanksrop.xyz'