apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s.tanksrop.xyz-media
spec:
  secretName: k8s.tanksrop.xyz
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.k8s.tanksrop.xyz'
  dnsNames:
  - '*.k8s.tanksrop.xyz'