apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-helm
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/tanksrop/kubernetes-configs
        revision: HEAD
        files:
          - path: helm/*/*/config.json
  template:
    metadata:
      name: '{{index .path.segments 2}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.repoURL}}'
          chart: '{{.chart}}'
          targetRevision: '{{.targetRevision}}'
          helm:
            valueFiles:
              - $values/helm/{{index .path.segments 1}}/{{index .path.segments 2}}/values.yaml
        - repoURL: https://github.com/tanksrop/kubernetes-configs
          targetRevision: HEAD
          ref: values
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
