apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-application
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.15.1
    helm:
      valuesObject: {}
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true