apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
  - protocol: TCP
    port: 8191
    targetPort: 8191
    nodePort: 30022
  type: NodePort