apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ddns
  labels:
    app: ddns
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ddns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ddns
    spec:
      containers:
      - image: mattolenik/cloudflare-ddns-client
        name: ddns
        env:
          - name: DOMAIN
            value: "taknsrop.xyz"
          - name: RECORD
            value: "k8s.tanksrop.xyz"
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-user-token
                key: password
        resources:
          limits:
            cpu: "1"
            memory: 64Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi

