apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.17.0
    helm:
      valuesObject:
        crds:
          enabled: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true